fix: :bug: transfertSelectOptions and more
cloud-pi-native/console pull request #1328
Opened 2024-08-21 09:34 UTC by KomsteRr

## Issues liées

Issues numéro: 

---------

## Quel est le comportement actuel ?

## Quel est le nouveau comportement ?

## Cette PR introduit-elle un breaking change ?

## Autres informations

2024-08-21 10:03 UTC, clairenollet commented on apps/client/src/components/TeamCt.vue
> +            v-if="transferSelectOptions.length <= 0"
`v-if="!transferSelectOptions.length"` (ça revient au même), à mettre plutôt directement dans la DsfrAlert

2024-08-21 10:03 UTC, clairenollet commented on apps/client/src/components/TeamCt.vue
> +            v-if="transferSelectOptions.length > 0"
ici tu peux mettre un `v-else`
et si tu voulais garder ton `v-if`, ce serait plutôt `v-if="transferSelectOptions.length"`

2024-08-21 10:59 UTC, this-is-tobi commented on apps/client/src/components/TeamCt.vue
> +              :title="transferSelectOptions.length"
On veut vraiment comme `title` la valeur `transferSelectOptions.length` ?

2024-08-21 13:38 UTC, clairenollet commented on apps/client/src/components/TeamCt.vue
> +const nextOwnerId = ref('' | undefined)
`const nextOwnerId = ref<string | undefined>(undefined)`

2024-08-21 13:38 UTC, clairenollet commented on apps/client/src/components/TeamCt.vue
>    ...props.project.members.map(member => ({
tu peux enlever le spread dans un tableau ici qui ne sert plus à rien

2024-08-21 16:00 UTC, clairenollet approved these changes

2024-08-21 16:42 UTC, this-is-tobi approved these changes

2024-08-22 09:23 UTC, ArnaudTA requested changes

2024-08-22 11:36 UTC, ArnaudTA commented on apps/client/src/components/TeamCt.vue
> +                @click="typeof nextOwnerId === 'string' ? transferOwnership(nextOwnerId) : null"
yep ça me va, en soit tu n'as pas forcément besoin de filer en argument une variable global mais ça ne me dérange pas spécialement

2024-08-22 11:37 UTC, ArnaudTA approved these changes

2024-08-22 11:43 UTC, ArnaudTA approved these changes

2024-08-22 12:40 UTC, merged