feat: ✨ add PAT
cloud-pi-native/console pull request #1439
Opened 2024-11-06 15:34 UTC by ArnaudTA

## Issues liées

Issues numéro:

---------

## Quel est le comportement actuel ?

## Quel est le nouveau comportement ?

## Cette PR introduit-elle un breaking change ?

## Autres informations

2024-11-14 09:17 UTC, mathieulaude commented on apps/server/src/resources/user/business.ts
> +export async function logViaToken<W extends boolean>(pass: string, withAdminPerms: W): Promise<W extends true ? ({ user: UserWithTokenId, adminPerms: bigint | undefined }) : UserWithTokenId | TokenIn
Pourquoi tant de haine ? :sweat_smile: 
Blague à part : ne serait-ce pas plus clair de créer 2 fonctions : avec et sans les permissions admin ?

2024-11-14 09:19 UTC, mathieulaude commented on apps/server/src/resources/user/business.ts
> +    return TokenInvalidReason.NOT_FOUND
Je verrais plutôt cette raison d'invalidité dans une exception que dans le return, dont on s'attend à avoir un token

2024-11-14 09:27 UTC, mathieulaude requested changes

2024-11-14 09:27 UTC, mathieulaude commented on apps/server/src/resources/user/business.ts
> +    return undefined
Pourquoi pas un `-1` ou une autre valeur notable pour identifier l'absence de roles ? le `undefined` me parait moins clair

2024-11-14 09:39 UTC, mathieulaude commented on apps/server/src/utils/controller.ts
> +        throw new Unauthorized401(resultToken)
Exception à lancer depuis la méthode driectement (cf remarque précédente)

2024-11-18 09:31 UTC, ArnaudTA commented on apps/server/src/utils/controller.ts
> +        throw new Unauthorized401(resultToken)
je comprend mais en essayant d'appliquer ce changement ça m'a posé un souci dans une autre fonction qui appelle logViaToken et logViaSession, du coup je préfère séparer le business qui ne doit jamais throw du controller/router qui lui peux se le permettre

2024-11-18 09:32 UTC, ArnaudTA commented on apps/server/src/resources/user/business.ts
> +    return undefined
boarf du coup j'ai tout passé tous les undefined à 0n c'est pas mal non plus

2024-11-18 09:44 UTC, mathieulaude commented on apps/server/src/resources/user/business.spec.ts
>      it('should create user and not return adminPerms', async () => {
```suggestion
    it('should create user and return empty adminPerms', async () => {
```

2024-11-18 09:46 UTC, mathieulaude submitted a review, later dismissed

2024-11-18 18:16 UTC, this-is-tobi commented on apps/server/src/resources/user/business.ts
> +    return undefined
Y'a une raison pour ne pas gérer ce cas dans `isTokenInvalid` avec un truc du style :
```ts
function isTokenInvalid(token: AdminToken | PersonalAccessToken | undefined): TokenInvalidReason | undefined {
  if (!token) {
    return TokenInvalidReason.NOT_FOUND
  }
  if (token.status !== 'active') {
    return TokenInvalidReason.INACTIVE
  }
  const currentDate = new Date()
  if (token.expirationDate && currentDate.getTime() > token.expirationDate?.getTime()) {
    return TokenInvalidReason.EXPIRED
  }
}
```

2024-11-18 18:16 UTC, this-is-tobi commented on apps/server/src/resources/user/business.ts
> +    return undefined
Pareil ici

2024-11-19 00:33 UTC, this-is-tobi submitted a review, later dismissed

2024-11-19 00:36 UTC, this-is-tobi approved these changes

2024-11-19 00:52 UTC, merged